<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Game.Domain\Game.Domain.csproj" />
    <ProjectReference Include="..\..\src\Game.Config\Game.Config.csproj" />
    <ProjectReference Include="..\..\src\Game.Engine\Game.Engine.csproj" />
    <ProjectReference Include="..\..\src\Game.Bots\Game.Bots.csproj" />
    <ProjectReference Include="..\..\src\Game.Balancing\Game.Balancing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\src\Game.Config\Samples\production-models\**\*.json" Link="Samples\production-models\%(RecursiveDir)%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\src\Game.Config\Samples\sessions\**\*.json" Link="Samples\sessions\%(RecursiveDir)%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
