<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Game.Domain\Game.Domain.csproj" />
    <ProjectReference Include="..\..\src\Game.Config\Game.Config.csproj" />
    <ProjectReference Include="..\..\src\Game.Engine\Game.Engine.csproj" />
    <ProjectReference Include="..\..\src\Game.Bots\Game.Bots.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\src\Game.Config\Samples\gameconfig.pilot.json" Link="Samples\gameconfig.pilot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\src\Game.Config\Samples\production-models\control-twin-metallurgy.json" Link="Samples\production-models\control-twin-metallurgy.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\src\Game.Config\Samples\sessions\pilot.json" Link="Samples\sessions\pilot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
